---@alias Tuple any
---@alias Objects Instance[]|any[]
---@alias Variant table<any,any>
---@alias Dictionary table<string,any>
---@alias Array Instance[]|any[]
---@alias Map table<any,any>
---@alias Function function
