---@alias int number
---@alias int64 number
---@alias double number
---@alias float number
---@alias bool boolean

---@alias Tuple any
---@alias Objects Instance[]|any[]
---@alias Variant table<any,any>
---@alias Dictionary table<string,any>
---@alias Array Instance[]|any[]
---@alias Map table<any,any>
---@alias Function function
